run_sanity_tests.sh  MANAGEMENT_SERVERS=n127
Loaded Config with SOCKET_PATH=unix:///tmp/csi.sock ,MANAGEMENT_SERVERS=n127
Initializing ManagementClient with managementServer=['https://n127']
NVMeshCSIDriver - INFO - Server is listening on unix:///tmp/csi.sock
Service started on pid 17058
waiting for service to be available
IdentityClient - DEBUG - calling method Probe with parameters {}
NVMeshCSIDriver - DEBUG - called method Probe
test_fails_on_empty_management_servers (test.sanity.test_config.TestConfigFile) ... ok
test_fails_on_missing_management_servers (test.sanity.test_config.TestConfigFile) ... ok
test_load (test.sanity.test_config.TestConfigFile) ... ok
test_get_plugin_capabilities (test.sanity.test_identity.TestIdentityService) ... IdentityClient - DEBUG - calling method GetPluginCapabilities with parameters {}
NVMeshCSIDriver - DEBUG - called method GetPluginCapabilities
ok
test_get_plugin_info (test.sanity.test_identity.TestIdentityService) ... capabilities {
  service {
    type: CONTROLLER_SERVICE
  }
}
capabilities {
  volume_expansion {
    type: ONLINE
  }
}

IdentityClient - DEBUG - calling method GetPluginInfo with parameters {}
NVMeshCSIDriver - DEBUG - called method GetPluginInfo
ok
test_probe (test.sanity.test_identity.TestIdentityService) ... IdentityClient - DEBUG - calling method Probe with parameters {}
NVMeshCSIDriver - DEBUG - called method Probe
ok
test_get_capabilities (test.sanity.test_node.TestNodeService) ... NodeClient - DEBUG - calling method NodeGetCapabilities with parameters {}
NVMeshCSIDriver - DEBUG - called method NodeGetCapabilities
ok
test_get_info (test.sanity.test_node.TestNodeService) ... NodeClient - DEBUG - calling method NodeGetInfo with parameters {}
NVMeshCSIDriver - DEBUG - called method NodeGetInfo
ok
test_node_expand_volume (test.sanity.test_node.TestNodeService) ... NodeClient - DEBUG - calling method NodeExpandVolume with parameters {"volumePath": "some_path", "volumeId": "vol_1"}
NVMeshCSIDriver - DEBUG - called method NodeExpandVolume
NVMeshCSIDriver - DEBUG - NodeExpandVolume called with request: {
  "volumePath": "some_path", 
  "volumeId": "vol_1"
}
Utils - DEBUG - running: df -T /dev/nvmesh/csi-1 | tail -1 | awk '{ print $2}'
Utils - DEBUG - cmd: df -T /dev/nvmesh/csi-1 | tail -1 | awk '{ print $2}' return exit_code=0 stdout= stderr=df: /dev/nvmesh/csi-1: No such file or directory

NVMeshCSIDriver - WARNING - Driver Error caught in gRPC call NodeExpandVolume - unknown fs_type 
ok
test_node_publish_volume (test.sanity.test_node.TestNodeService) ... NodeClient - DEBUG - calling method NodePublishVolume with parameters {"volumeCapability": {"accessMode": {"mode": "MULTI_NODE_MULTI_WRITER"}, "mount": {"fsType": "ext4"}}, "targetPath": "/publish/vol_1", "volumeId": "vol_1"}
NVMeshCSIDriver - DEBUG - called method NodePublishVolume
NVMeshCSIDriver - DEBUG - NodePublishVolume called with request: {
  "volumeCapability": {
    "accessMode": {
      "mode": "MULTI_NODE_MULTI_WRITER"
    }, 
    "mount": {
      "fsType": "ext4"
    }
  }, 
  "targetPath": "/publish/vol_1", 
  "volumeId": "vol_1"
}
Utils - DEBUG - running: ls /dev/nvmesh/csi-1
Utils - DEBUG - cmd: ls /dev/nvmesh/csi-1 return exit_code=2 stdout= stderr=ls: cannot access '/dev/nvmesh/csi-1': No such file or directory

NVMeshCSIDriver - WARNING - Driver Error caught in gRPC call NodePublishVolume - nvmesh volume csi-1 was not found under /dev/nvmesh/
ok
test_node_stage_volume_fail_with_no_block_device (test.sanity.test_node.TestNodeService) ... NodeClient - DEBUG - calling method NodeStageVolume with parameters {"stagingTargetPath": "/stage/vol_1", "volumeCapability": {"accessMode": {"mode": "MULTI_NODE_MULTI_WRITER"}, "block": {}}, "volumeId": "vol_1"}
NVMeshCSIDriver - DEBUG - called method NodeStageVolume
NVMeshCSIDriver - DEBUG - NodeStageVolume called with request: {
  "stagingTargetPath": "/stage/vol_1", 
  "volumeCapability": {
    "accessMode": {
      "mode": "MULTI_NODE_MULTI_WRITER"
    }, 
    "block": {}
  }, 
  "volumeId": "vol_1"
}
Utils - DEBUG - running: python /host/bin/nvmesh_attach_volumes csi-1
Utils - DEBUG - cmd: python /host/bin/nvmesh_attach_volumes csi-1 return exit_code=2 stdout= stderr=python: can't open file '/host/bin/nvmesh_attach_volumes': [Errno 2] No such file or directory

NVMeshCSIDriver - WARNING - Driver Error caught in gRPC call NodeStageVolume - local attach failed: exit_code: 2 stdout:  stderr: python: can't open file '/host/bin/nvmesh_attach_volumes': [Errno 2] No such file or directory

ok
test_node_unpublish_volume (test.sanity.test_node.TestNodeService) ... NodeClient - DEBUG - calling method NodeUnpublishVolume with parameters {"targetPath": "/mnt/vol_1", "volumeId": "vol_1"}
NVMeshCSIDriver - DEBUG - called method NodeUnpublishVolume
NVMeshCSIDriver - DEBUG - NodeUnpublishVolume called with request: {
  "targetPath": "/mnt/vol_1", 
  "volumeId": "vol_1"
}
NVMeshCSIDriver - WARNING - Driver Error caught in gRPC call NodeUnpublishVolume - mount path /mnt/vol_1 not found
ok
test_node_unstage_volume (test.sanity.test_node.TestNodeService) ... NodeClient - DEBUG - calling method NodeUnstageVolume with parameters {"stagingTargetPath": "/stage/vol_1", "volumeId": "vol_1"}
NVMeshCSIDriver - DEBUG - called method NodeUnstageVolume
NVMeshCSIDriver - DEBUG - NodeUnstageVolume called with request: {
  "stagingTargetPath": "/stage/vol_1", 
  "volumeId": "vol_1"
}
NVMeshCSIDriver - WARNING - Driver Error caught in gRPC call NodeUnstageVolume - mount path /stage/vol_1 not found
ok
test_controller_expand_volume (test.sanity.test_controller.TestControllerService) ... ControllerClient - DEBUG - calling method CreateVolume with parameters {"volumeCapabilities": [{"accessMode": {"mode": "MULTI_NODE_MULTI_WRITER"}}, {"block": {}}], "parameters": {"vpg": "DEFAULT_CONCATENATED_VPG"}, "name": "vol_to_extend", "capacityRange": {"requiredBytes": "5368709120"}}
NVMeshCSIDriver - DEBUG - called method CreateVolume
NVMeshCSIDriver - DEBUG - create volume request: {
  "volumeCapabilities": [
    {
      "accessMode": {
        "mode": "MULTI_NODE_MULTI_WRITER"
      }
    }, 
    {
      "block": {}
    }
  ], 
  "parameters": {
    "vpg": "DEFAULT_CONCATENATED_VPG"
  }, 
  "name": "vol_to_extend", 
  "capacityRange": {
    "requiredBytes": "5368709120"
  }
}
NVMeshCSIDriver - DEBUG - create volume parameters: {u'vpg': u'DEFAULT_CONCATENATED_VPG'}
NVMeshCSIDriver - DEBUG - Creating Volume from VPG DEFAULT_CONCATENATED_VPG
InfraClient.ManagementClient[17048]: DEBUG: capacity = 5368709120
InfraClient.ManagementClient[17048]: DEBUG: request method=post url=https://n127/volumes/save payload={'edit': [], 'create': [{'VPG': u'DEFAULT_CONCATENATED_VPG', 'RAIDLevel': 'Concatenated', 'capacity': 5368709120L, 'name': u'csi-to_extend', 'description': '{"volume_capabilities": [{"accessMode": {"mode": "MULTI_NODE_MULTI_WRITER"}}, {"block": {}}], "csi_name": "vol_to_extend"}'}], 'remove': []} retries=0
InfraClient.ManagementClient[17048]: DEBUG: request method=post url=https://n127/volumes/save payload={'edit': [], 'create': [{'VPG': u'DEFAULT_CONCATENATED_VPG', 'RAIDLevel': 'Concatenated', 'capacity': 5368709120L, 'name': u'csi-to_extend', 'description': '{"volume_capabilities": [{"accessMode": {"mode": "MULTI_NODE_MULTI_WRITER"}}, {"block": {}}], "csi_name": "vol_to_extend"}'}], 'remove': []} retries=1
InfraClient.ManagementClient[17048]: DEBUG: request method=post url=https://n127/volumes/save payload={'edit': [], 'create': [{'VPG': u'DEFAULT_CONCATENATED_VPG', 'RAIDLevel': 'Concatenated', 'capacity': 5368709120L, 'name': u'csi-to_extend', 'description': '{"volume_capabilities": [{"accessMode": {"mode": "MULTI_NODE_MULTI_WRITER"}}, {"block": {}}], "csi_name": "vol_to_extend"}'}], 'remove': []} retries=2
NVMeshCSIDriver - WARNING - Error caught in gRPC call CreateVolume - <class 'managementClient.ManagementClient.ManagementTimeout'>: ('Could not connect to Management at /volumes/save', 'Timeout from all Management Servers (https://n127)') in controller_service.py on line: 63
ERROR
test_controller_get_capabilities (test.sanity.test_controller.TestControllerService) ... ControllerClient - DEBUG - calling method ControllerGetCapabilities with parameters {}
NVMeshCSIDriver - DEBUG - called method ControllerGetCapabilities
ok
test_create_volume (test.sanity.test_controller.TestControllerService) ... ControllerClient - DEBUG - calling method CreateVolume with parameters {"volumeCapabilities": [{"accessMode": {"mode": "MULTI_NODE_MULTI_WRITER"}}, {"block": {}}], "parameters": {"vpg": "DEFAULT_CONCATENATED_VPG"}, "name": "vol_1", "capacityRange": {"requiredBytes": "5368709120"}}
NVMeshCSIDriver - DEBUG - called method CreateVolume
NVMeshCSIDriver - DEBUG - create volume request: {
  "volumeCapabilities": [
    {
      "accessMode": {
        "mode": "MULTI_NODE_MULTI_WRITER"
      }
    }, 
    {
      "block": {}
    }
  ], 
  "parameters": {
    "vpg": "DEFAULT_CONCATENATED_VPG"
  }, 
  "name": "vol_1", 
  "capacityRange": {
    "requiredBytes": "5368709120"
  }
}
NVMeshCSIDriver - DEBUG - create volume parameters: {u'vpg': u'DEFAULT_CONCATENATED_VPG'}
NVMeshCSIDriver - DEBUG - Creating Volume from VPG DEFAULT_CONCATENATED_VPG
InfraClient.ManagementClient[17048]: DEBUG: capacity = 5368709120
InfraClient.ManagementClient[17048]: DEBUG: request method=post url=https://n127/volumes/save payload={'edit': [], 'create': [{'VPG': u'DEFAULT_CONCATENATED_VPG', 'RAIDLevel': 'Concatenated', 'capacity': 5368709120L, 'name': u'csi-1', 'description': '{"volume_capabilities": [{"accessMode": {"mode": "MULTI_NODE_MULTI_WRITER"}}, {"block": {}}], "csi_name": "vol_1"}'}], 'remove': []} retries=0
InfraClient.ManagementClient[17048]: DEBUG: request method=post url=https://n127/volumes/save payload={'edit': [], 'create': [{'VPG': u'DEFAULT_CONCATENATED_VPG', 'RAIDLevel': 'Concatenated', 'capacity': 5368709120L, 'name': u'csi-1', 'description': '{"volume_capabilities": [{"accessMode": {"mode": "MULTI_NODE_MULTI_WRITER"}}, {"block": {}}], "csi_name": "vol_1"}'}], 'remove': []} retries=1
InfraClient.ManagementClient[17048]: DEBUG: request method=post url=https://n127/volumes/save payload={'edit': [], 'create': [{'VPG': u'DEFAULT_CONCATENATED_VPG', 'RAIDLevel': 'Concatenated', 'capacity': 5368709120L, 'name': u'csi-1', 'description': '{"volume_capabilities": [{"accessMode": {"mode": "MULTI_NODE_MULTI_WRITER"}}, {"block": {}}], "csi_name": "vol_1"}'}], 'remove': []} retries=2
NVMeshCSIDriver - WARNING - Error caught in gRPC call CreateVolume - <class 'managementClient.ManagementClient.ManagementTimeout'>: ('Could not connect to Management at /volumes/save', 'Timeout from all Management Servers (https://n127)') in controller_service.py on line: 63
ERROR
test_delete_volume (test.sanity.test_controller.TestControllerService) ... ControllerClient - DEBUG - calling method DeleteVolume with parameters {"volumeId": "vol_1"}
NVMeshCSIDriver - DEBUG - called method DeleteVolume
InfraClient.ManagementClient[17048]: DEBUG: request method=post url=https://n127/volumes/save payload={'edit': [], 'create': [], 'remove': [{'_id': u'csi-1'}]} retries=0
InfraClient.ManagementClient[17048]: DEBUG: request method=post url=https://n127/volumes/save payload={'edit': [], 'create': [], 'remove': [{'_id': u'csi-1'}]} retries=1
InfraClient.ManagementClient[17048]: DEBUG: request method=post url=https://n127/volumes/save payload={'edit': [], 'create': [], 'remove': [{'_id': u'csi-1'}]} retries=2
NVMeshCSIDriver - WARNING - Error caught in gRPC call DeleteVolume - <class 'managementClient.ManagementClient.ManagementTimeout'>: ('Could not connect to Management at /volumes/save', 'Timeout from all Management Servers (https://n127)') in controller_service.py on line: 94
ERROR
test_fail_to_create_existing_volume (test.sanity.test_controller.TestControllerService) ... ControllerClient - DEBUG - calling method CreateVolume with parameters {"volumeCapabilities": [{"accessMode": {"mode": "MULTI_NODE_MULTI_WRITER"}}, {"block": {}}], "parameters": {"vpg": "DEFAULT_CONCATENATED_VPG"}, "name": "vol_1", "capacityRange": {"requiredBytes": "8589934592"}}
NVMeshCSIDriver - DEBUG - called method CreateVolume
NVMeshCSIDriver - DEBUG - create volume request: {
  "volumeCapabilities": [
    {
      "accessMode": {
        "mode": "MULTI_NODE_MULTI_WRITER"
      }
    }, 
    {
      "block": {}
    }
  ], 
  "parameters": {
    "vpg": "DEFAULT_CONCATENATED_VPG"
  }, 
  "name": "vol_1", 
  "capacityRange": {
    "requiredBytes": "8589934592"
  }
}
NVMeshCSIDriver - DEBUG - create volume parameters: {u'vpg': u'DEFAULT_CONCATENATED_VPG'}
NVMeshCSIDriver - DEBUG - Creating Volume from VPG DEFAULT_CONCATENATED_VPG
InfraClient.ManagementClient[17048]: DEBUG: capacity = 8589934592
InfraClient.ManagementClient[17048]: DEBUG: request method=post url=https://n127/volumes/save payload={'edit': [], 'create': [{'VPG': u'DEFAULT_CONCATENATED_VPG', 'RAIDLevel': 'Concatenated', 'capacity': 8589934592L, 'name': u'csi-1', 'description': '{"volume_capabilities": [{"accessMode": {"mode": "MULTI_NODE_MULTI_WRITER"}}, {"block": {}}], "csi_name": "vol_1"}'}], 'remove': []} retries=0
InfraClient.ManagementClient[17048]: DEBUG: request method=post url=https://n127/volumes/save payload={'edit': [], 'create': [{'VPG': u'DEFAULT_CONCATENATED_VPG', 'RAIDLevel': 'Concatenated', 'capacity': 8589934592L, 'name': u'csi-1', 'description': '{"volume_capabilities": [{"accessMode": {"mode": "MULTI_NODE_MULTI_WRITER"}}, {"block": {}}], "csi_name": "vol_1"}'}], 'remove': []} retries=1
InfraClient.ManagementClient[17048]: DEBUG: request method=post url=https://n127/volumes/save payload={'edit': [], 'create': [{'VPG': u'DEFAULT_CONCATENATED_VPG', 'RAIDLevel': 'Concatenated', 'capacity': 8589934592L, 'name': u'csi-1', 'description': '{"volume_capabilities": [{"accessMode": {"mode": "MULTI_NODE_MULTI_WRITER"}}, {"block": {}}], "csi_name": "vol_1"}'}], 'remove': []} retries=2
NVMeshCSIDriver - WARNING - Error caught in gRPC call CreateVolume - <class 'managementClient.ManagementClient.ManagementTimeout'>: ('Could not connect to Management at /volumes/save', 'Timeout from all Management Servers (https://n127)') in controller_service.py on line: 63
ok
test_list_volumes (test.sanity.test_controller.TestControllerService) ... ControllerClient - DEBUG - calling method ListVolumes with parameters {"maxEntries": 2}
NVMeshCSIDriver - DEBUG - called method ListVolumes
InfraClient.ManagementClient[17048]: DEBUG: request method=get url=https://n127/volumes/all/0/2/ payload={'filter': '{}', 'sort': '{}', 'projection': '{"_id": 1, "capacity": 1}'} retries=0
InfraClient.ManagementClient[17048]: DEBUG: request method=get url=https://n127/volumes/all/0/2/ payload={'filter': '{}', 'sort': '{}', 'projection': '{"_id": 1, "capacity": 1}'} retries=1
InfraClient.ManagementClient[17048]: DEBUG: request method=get url=https://n127/volumes/all/0/2/ payload={'filter': '{}', 'sort': '{}', 'projection': '{"_id": 1, "capacity": 1}'} retries=2
NVMeshCSIDriver - WARNING - Error caught in gRPC call ListVolumes - <class 'managementClient.ManagementClient.ManagementTimeout'>: ('Could not connect to Management at /volumes/all/0/2/', 'Timeout from all Management Servers (https://n127)') in controller_service.py on line: 188
ERROR
test_validate_volume_capabilities (test.sanity.test_controller.TestControllerService) ... ControllerClient - DEBUG - calling method ValidateVolumeCapabilities with parameters {"volumeId": "vol_1", "volumeCapabilities": [{"accessMode": {"mode": "MULTI_NODE_MULTI_WRITER"}}, {"block": {}}]}
NVMeshCSIDriver - DEBUG - called method ValidateVolumeCapabilities
InfraClient.ManagementClient[17048]: DEBUG: request method=get url=https://n127/volumes/all/0/0/ payload={'filter': '{"_id": "csi-1"}', 'sort': '{}', 'projection': '{"status": 1, "_id": 1, "capacity": 1, "description": 1}'} retries=0
InfraClient.ManagementClient[17048]: DEBUG: request method=get url=https://n127/volumes/all/0/0/ payload={'filter': '{"_id": "csi-1"}', 'sort': '{}', 'projection': '{"status": 1, "_id": 1, "capacity": 1, "description": 1}'} retries=1
InfraClient.ManagementClient[17048]: DEBUG: request method=get url=https://n127/volumes/all/0/0/ payload={'filter': '{"_id": "csi-1"}', 'sort': '{}', 'projection': '{"status": 1, "_id": 1, "capacity": 1, "description": 1}'} retries=2
NVMeshCSIDriver - WARNING - Error caught in gRPC call ValidateVolumeCapabilities - <class 'managementClient.ManagementClient.ManagementTimeout'>: ('Could not connect to Management at /volumes/all/0/0/', 'Timeout from all Management Servers (https://n127)') in controller_service.py on line: 157
ERROR

======================================================================
ERROR: test_controller_expand_volume (test.sanity.test_controller.TestControllerService)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/sanity/helpers/error_handlers.py", line 26, in func_wrapper
    handleGRPCError(func.__name__, ex)
  File "test/sanity/helpers/error_handlers.py", line 13, in handleGRPCError
    raise grpcError
_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "<class 'managementClient.ManagementClient.ManagementTimeout'>: ('Could not connect to Management at /volumes/save', 'Timeout from all Management Servers (https://n127)') in controller_service.py on line: 63"
	debug_error_string = "{"created":"@1568916978.073138389","description":"Error received from peer unix:/tmp/csi.sock","file":"src/core/lib/surface/call.cc","file_line":1041,"grpc_message":"<class 'managementClient.ManagementClient.ManagementTimeout'>: ('Could not connect to Management at /volumes/save', 'Timeout from all Management Servers (https://n127)') in controller_service.py on line: 63","grpc_status":13}"
>

======================================================================
ERROR: test_create_volume (test.sanity.test_controller.TestControllerService)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/sanity/helpers/error_handlers.py", line 26, in func_wrapper
    handleGRPCError(func.__name__, ex)
  File "test/sanity/helpers/error_handlers.py", line 13, in handleGRPCError
    raise grpcError
_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "<class 'managementClient.ManagementClient.ManagementTimeout'>: ('Could not connect to Management at /volumes/save', 'Timeout from all Management Servers (https://n127)') in controller_service.py on line: 63"
	debug_error_string = "{"created":"@1568916978.361968279","description":"Error received from peer unix:/tmp/csi.sock","file":"src/core/lib/surface/call.cc","file_line":1041,"grpc_message":"<class 'managementClient.ManagementClient.ManagementTimeout'>: ('Could not connect to Management at /volumes/save', 'Timeout from all Management Servers (https://n127)') in controller_service.py on line: 63","grpc_status":13}"
>

======================================================================
ERROR: test_delete_volume (test.sanity.test_controller.TestControllerService)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/sanity/helpers/error_handlers.py", line 26, in func_wrapper
    handleGRPCError(func.__name__, ex)
  File "test/sanity/helpers/error_handlers.py", line 13, in handleGRPCError
    raise grpcError
_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "<class 'managementClient.ManagementClient.ManagementTimeout'>: ('Could not connect to Management at /volumes/save', 'Timeout from all Management Servers (https://n127)') in controller_service.py on line: 94"
	debug_error_string = "{"created":"@1568916978.642026691","description":"Error received from peer unix:/tmp/csi.sock","file":"src/core/lib/surface/call.cc","file_line":1041,"grpc_message":"<class 'managementClient.ManagementClient.ManagementTimeout'>: ('Could not connect to Management at /volumes/save', 'Timeout from all Management Servers (https://n127)') in controller_service.py on line: 94","grpc_status":13}"
>

======================================================================
ERROR: test_list_volumes (test.sanity.test_controller.TestControllerService)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/sanity/helpers/error_handlers.py", line 26, in func_wrapper
    handleGRPCError(func.__name__, ex)
  File "test/sanity/helpers/error_handlers.py", line 13, in handleGRPCError
    raise grpcError
_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "<class 'managementClient.ManagementClient.ManagementTimeout'>: ('Could not connect to Management at /volumes/all/0/2/', 'Timeout from all Management Servers (https://n127)') in controller_service.py on line: 188"
	debug_error_string = "{"created":"@1568916979.212919665","description":"Error received from peer unix:/tmp/csi.sock","file":"src/core/lib/surface/call.cc","file_line":1041,"grpc_message":"<class 'managementClient.ManagementClient.ManagementTimeout'>: ('Could not connect to Management at /volumes/all/0/2/', 'Timeout from all Management Servers (https://n127)') in controller_service.py on line: 188","grpc_status":13}"
>

======================================================================
ERROR: test_validate_volume_capabilities (test.sanity.test_controller.TestControllerService)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/sanity/helpers/error_handlers.py", line 26, in func_wrapper
    handleGRPCError(func.__name__, ex)
  File "test/sanity/helpers/error_handlers.py", line 13, in handleGRPCError
    raise grpcError
_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "<class 'managementClient.ManagementClient.ManagementTimeout'>: ('Could not connect to Management at /volumes/all/0/0/', 'Timeout from all Management Servers (https://n127)') in controller_service.py on line: 157"
	debug_error_string = "{"created":"@1568916979.494519515","description":"Error received from peer unix:/tmp/csi.sock","file":"src/core/lib/surface/call.cc","file_line":1041,"grpc_message":"<class 'managementClient.ManagementClient.ManagementTimeout'>: ('Could not connect to Management at /volumes/all/0/0/', 'Timeout from all Management Servers (https://n127)') in controller_service.py on line: 157","grpc_status":13}"
>

----------------------------------------------------------------------
Ran 20 tests in 1.937s

FAILED (errors=5)
<unittest.runner.TextTestResult run=20 errors=5 failures=0>
Sanity Tests Failed
